_target_: torch.utils.data.DataLoader

dataset:
  _target_: projects.DC_prediction.datasets.railroad.RailroadDataset
  mode: train
  val_type: pre
  window_length: 2500
  history_length: 500
  rail_type: curved
  interval: 30

batch_size: 4
num_workers: 4
pin_memory: True
prefetch_factor: 2
drop_last: False
