_target_: torch.utils.data.DataLoader

dataset:
  _target_: projects.DC_prediction.datasets.railroad.RailroadDataset
  mode: train
  val_type: pre  # [pre, post, wo]
  window_length: 2500
  history_length: 500
  rail_type: curved  # [curved, straight, both]
  interval: 30
  augmentation:
    gaussian_smoothing:
      p: 0.5
      mode: uniform
      min_sigma: 0.001
      max_sigma: 0.1
      sigma_normal_scale: 2.0
    rescale_time:
      p: 0.5
      min_scale_factor: 1.0  # 작은 사이즈로 resize되고 zero padding하게되면 정의된 문제에 적당하지 않으므로, 1.0으로 세팅할 것.
      max_scale_factor: 2.0


batch_size: 4
num_workers: 0
pin_memory: True
prefetch_factor: 2
drop_last: False
