version: '3.0'  # YAML 파일 포맷 버전
services:
  ml-base:
    image: ${IMAGE_NAME_BASE}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_BASE}

  ml-dev:
    hostname: ml-dev
    image: ${IMAGE_NAME_DEV}
    container_name: ${CONTAINER_NAME_DEV}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
    working_dir: ${WORKDIR_PATH}
    # user: ${UID}:${GID}
    build:
      target: ${TARGET_STAGE:-train}
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_DEV}
      args: 
        BASE_IMAGE: ${IMAGE_NAME_BASE}
        WORKDIR_PATH: ${WORKDIR_PATH:-/opt/ml}
        GRP: ${GRP:-noname}
        USR: ${USR:-noname}
        GID: ${GID:-noname}
        UID: ${UID:-noname}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  ml-dev-mac:
    hostname: ml-dev-mac
    image: ${IMAGE_NAME_DEV_MAC}
    container_name: ${CONTAINER_NAME_DEV_MAC}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
    working_dir: ${WORKDIR_PATH}
    # user: ${UID}:${GID}
    build:
      target: ${TARGET_STAGE:-train}
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_DEV_MAC}
      args: 
        BASE_IMAGE: ${IMAGE_NAME_BASE}
        WORKDIR_PATH: ${WORKDIR_PATH:-/opt/ml}
        GRP: ${GRP:-noname}
        USR: ${USR:-noname}
        GID: ${GID:-noname}
        UID: ${UID:-noname}
