version: '3.0'  # YAML 파일 포맷 버전
services:
  railroad-base:
    image: ${IMAGE_NAME_BASE}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_BASE}

  railroad-dev:
    hostname: railroad-dev
    image: ${IMAGE_NAME_DEV}
    container_name: ${CONTAINER_NAME_DEV}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
      - ${DATA_PATH}:/data/railroad
    working_dir: ${WORKDIR_PATH}
    build:
      target: ${TARGET_STAGE:-train}
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_DEV}
      args: 
        BASE_IMAGE: ${IMAGE_NAME_BASE}
        WORKDIR_PATH: ${WORKDIR_PATH:-/opt/railroad}
        GRP: ${GRP:-noname}
        USR: ${USR:-noname}
        GID: ${GID:-noname}
        UID: ${UID:-noname}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
