# Reference :
# https://github.com/anibali/docker-pytorch/blob/master/dockerfiles/1.11.0-cuda11.5-ubuntu20.04/Dockerfile
# base image
FROM nvidia/cuda:11.6.2-base-ubuntu20.04

# maintainer
LABEL maintainer "chpark <bch0322@gmail.com>"

# set timezone
ENV TZ="Asia/Seoul"
RUN apt-get update && DEBIAN_FRONTEND=noninterative apt-get install tzdata
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata
    
# Remove any third-party apt sources to avoid issues with expiring keys.
RUN rm -f /etc/apt/sources.list.d/*.list

# Install some basic utilities
RUN apt-get update && apt-get -y --no-install-recommends install \
    python3-dev \
    python3-pip \
    git \
 && rm -rf /var/lib/apt/lists/*

#######################################
RUN pip3 install --upgrade pip
RUN pip3 install pytest pytest-env gputil

# Install requirements
COPY requirements_base.txt /requirements_base.txt
RUN pip3 --no-cache-dir install -r /requirements_base.txt

# 설치로 생성된 캐시 파일들을 삭제해서 용량 줄이기!
RUN apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/cache/* && \
    rm -rf /var/lib/log/*

# Set the default command to python3
CMD ["/bin/bash"]
