_target_: projects.DC_prediction.models.unet_3d_cls.model

in_channels: 1
mid_channels: 96
out_channels: 1
target_attr: ${trainer.target_attr}
target_attr_to_train: ${trainer.fine_tune_info.target_attr_to_train}
fpn_n_layers: 2
f_maps: 24
num_levels: 4
num_groups: 4
